name: quang_hung_hai_weather_application
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  map: ^1.0.0
  latlng: ^0.1.0
  cached_network_image: ^3.2.0

dev_dependencies:
  mocktail: ^0.2.0
  mockito: ^5.0.17
  bloc_test: ^9.0.2
  test: ^1.17.12
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/config/env/
    - assets/images/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helveticaneue.ttf
    - family: Helvetica Neue Light
      fonts:
        - asset: assets/fonts/helveticaneuelight.ttf
