name: quang_hung_hai_weather_application
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  after_layout: ^1.1.0
  bloc: ^8.0.2
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.3
  flutter_simple_dependency_injection: ^2.0.0
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  map:
  latlng:
  syncfusion_flutter_charts: ^19.3.54
  fl_chart: ^0.41.0
  intl: ^0.17.0
  substring_highlight: ^1.0.33

dev_dependencies:
  mocktail: ^0.2.0
  mockito: ^5.0.17
  bloc_test: ^9.0.2
  test: ^1.17.12
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/config/env/

  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helveticaneue.ttf
          weight: 400
        - asset: assets/fonts/helveticaneuelight.ttf
          weight: 300
        - asset: assets/fonts/HelveticaNeue-Thin.ttf
          weight: 100
